### ISSUE TITLE
2.0 release

### ISSUE THREAD

**Issue by ejmahler** [awelkie/RustFFT#17]
Hello :)

I'm preparing to release my DCT crate on crates.io soon: https://github.com/ejmahler/rust_dct

It relies on the latest code from rustFFT, and crates.io doesn't allow github dependencies, so rustFFT will need a release with its latest code before I can publish it.

There's one thing that I know of that needs to be done before a 2.0 release: documentation, examples, etc. It sounded like you wanted to do this, but if you decide you don't have enough time, I'd be glad to help.

And if there are any other changes you have in mind, again I'd be glad to help. Let me know what I can do to make the release easier!

**Comment by awelkie** [comment]
Yeah, documentation and examples are the big ones. I also wanted to play around with the API for a bit to make sure it makes sense. I would appreciate some help with the documentation and examples, and I'll try to mess around with the new API some more soon so I can feel good about releasing it.

Thanks so much for all your help, by the way!

**Comment by awelkie** [comment]
I haven't forgotten about this, just been a little busy with work.

I do have one thought, though. I was thinking about changing the occurrences of `Rc<FFT>` to `B where B: Borrow<FFT>`. This is a little more generic than `Rc<FFT>`, and I think it'll allow for `#[no_std]` uses. The planner would still need to box the `FFT` trait objects in a box or an `Rc`, but a user could build their own FFT algorithms using stack objects and references. Any thoughts?

**Comment by ejmahler** [comment]
Can you give an example of how it would be used to make a stack variable? I've never seen this before. Does it just take anything that dereferences to a FFT instance?

**Comment by awelkie** [comment]
Yes. So references would work the same as `Box` or `Rc`. It's more general than requiring an `Rc`, but it can make for a weirder interface because you have to specify the lifetime each time, which for `Rc` or `Box` is just `'static`. I think it would be worth it if we could get `#[no_std]` usage, but in order to do that we would also have to change the usage of `Vec` to something that can exist on bare metal, and I'm not sure how to do that and also keep a sane API. So I don't think we should change anything for now until we have a good plan for `#[no_std]`.

Sorry for taking some time with the 2.0 release. I haven't had a chance to really play with the API much, and it's something I want to do before committing to a 2.0 release. This is obviously quite a large API change, and since this library is post 1.0 I want to make sure to get it right to avoid unnecessary major version number churn. Things are settling down for me with work, so I should have some more time to commit to this in the near term.

The one thing I do want to change is to get rid of `process_multi` from the `FFT` trait. It's something that doesn't seem to be specialized for any of the implementors and all of them basically perform the same for-loop. So I don't think it belongs in the `FFT` trait definition. Do you know of any FFT algorithms that would benefit from having a specialized implementation of `process_multi`?

Also, I would like to revisit the use of `Rc` for the internal data for the FFTs. Using `Rc` makes the FFT structures `!Send`, which means they can't be used across thread boundaries. Which is unfortunate, because since there's no other reason a single `FFT` structure couldn't be used across thread boundaries. On the other hand, using `Rc` allows for the re-use of twiddle factors and other data. One option would be to use `Arc` instead of `Rc`. This would be one benefit of using `Borrow`, as the user could choose their pointer type if they wanted.

I could also imagine a use case where a user could be allocating FFTs for an arbitrary number of lengths. If they were to use the provided `FFTplanner`, this could be a potential memory leak because the `HashMap` of the planner would always grow.. So I think some users would want to do their own caching, but still take advantage of the provided planner. So maybe there should be some way to invoke the `plan` algorithm once and bypass the `HashMap`?

**Comment by ejmahler** [comment]
> Sorry for taking some time with the 2.0 release. I haven't had a chance to really play with the API much, and it's something I want to do before committing to a 2.0 release. This is obviously quite a large API change, and since this library is post 1.0 I want to make sure to get it right to avoid unnecessary major version number churn. Things are settling down for me with work, so I should have some more time to commit to this in the near term.

No problem!

> Also, I would like to revisit the use of Rc for the internal data for the FFTs. Using Rc makes the FFT structures !Send, which means they can't be used across thread boundaries. Which is unfortunate, because since there's no other reason a single FFT structure couldn't be used across thread boundaries. On the other hand, using Rc allows for the re-use of twiddle factors and other data. One option would be to use Arc instead of Rc. This would be one benefit of using Borrow, as the user could choose their pointer type if they wanted.

I benchmarked the planner with Rc and again with Arc, and found no discernible difference between Rc and Arc. This make sense, because the planner is doing much more expensive things, like calls to sin() and cos(), allocations, etc. And in the case of prime factors, it's going as far as computing a FFT. So the cost of incrementing an atomic refcount instead of a non-atomic refcount is negligible. And using Arc vs Rc should have absolutely no effect on performance after setup is complete.

And given the problem space and that FFT instances are immutable, it only makes sense to take steps to support multiple threads. So I think this is a good change.

**Comment by ejmahler** [comment]
> The one thing I do want to change is to get rid of process_multi from the FFT trait. It's something that doesn't seem to be specialized for any of the implementors and all of them basically perform the same for-loop. So I don't think it belongs in the FFT trait definition. Do you know of any FFT algorithms that would benefit from having a specialized implementation of process_multi?

I originally added this as a performance thing. Basically, when you call process_multi, it only has to perform one assert and one virtual call, vs dozens of size asserts and dozens of virtual calls. To make sure it actually was giving a performance benefit, I ran a benchmark with it is as is now, and a benchmark where I modified MixedRadix to call process() instead of process_multi(). Across the board, any FFT size that used MixedRadix performed 5-10% better when calling process_multi vs process().

Regarding specializations, I do have a potential specialization in mind. There are two variants of Rader's Algorithm, one where the inner FFT size is `n - 1` and another where the inner FFT size is the next power of two`>= 2 * n - 3`. The second variant has more consistent performance, but requires much more scratch space (IT it can't use the input buffer as scratch space). While the first variant has inconsistent performance, but requires a "normal" amount of scratch space. RustFFT currently uses the first variant.

If we were to add the other variant of rader's algorithm, it would be used in cases where we know the first variant will perform poorly (cunningham chains). Because it would be used so rarely and because it would have special needs for scratch space, we could allocate the scratch within process(), and let it de-allocate when process() finishes. In this case, having a process_multi() would let us allocate the scratch once for many FFTs, rather than once per FFT.

**Comment by ejmahler** [comment]
> I could also imagine a use case where a user could be allocating FFTs for an arbitrary number of lengths. If they were to use the provided FFTplanner, this could be a potential memory leak because the HashMap of the planner would always grow.. So I think some users would want to do their own caching, but still take advantage of the provided planner. So maybe there should be some way to invoke the plan algorithm once and bypass the HashMap?

I think this is a question of documentation. If you drop a FFTplanner, its cache is cleared, and any FFT instances that are only referred to by the cache are deleted. So users who plan to create lots of FFTs of different sizes and are worried about memory usage should regularly drop() the FFT planner.

It would be a lot of work to add a second non-caching variant of plan_fft. It can be done, but I'd make sure it's a use case that proper documentation won't solve.

**Comment by awelkie** [comment]
> I benchmarked the planner with Rc and again with Arc, and found no discernible difference between Rc and Arc. This make sense, because the planner is doing much more expensive things, like calls to sin() and cos(), allocations, etc. And in the case of prime factors, it's going as far as computing a FFT. So the cost of incrementing an atomic refcount instead of a non-atomic refcount is negligible. And using Arc vs Rc should have absolutely no effect on performance after setup is complete.

> And given the problem space and that FFT instances are immutable, it only makes sense to take steps to support multiple threads. So I think this is a good change.

Yeah, I wouldn't expect much of a performance hit at all. I agree with `Arc` being the way to go.

> I originally added this as a performance thing. Basically, when you call process_multi, it only has to perform one assert and one virtual call, vs dozens of size asserts and dozens of virtual calls. To make sure it actually was giving a performance benefit, I ran a benchmark with it is as is now, and a benchmark where I modified MixedRadix to call process() instead of process_multi(). Across the board, any FFT size that used MixedRadix performed 5-10% better when calling process_multi vs process().

Oh, that's interesting. I wonder if there's a way to avoid the virtual call look up each time. Like if you can store the function pointer in a separate variable and call that directly. Either way, I think I'll just keep the `process_multi` method, except I'll implement it in the trait definition to reduce code duplication. But that's not a blocker for 2.0.

> I think this is a question of documentation. If you drop a FFTplanner, its cache is cleared, and any FFT instances that are only referred to by the cache are deleted. So users who plan to create lots of FFTs of different sizes and are worried about memory usage should regularly drop() the FFT planner.

> It would be a lot of work to add a second non-caching variant of plan_fft. It can be done, but I'd make sure it's a use case that proper documentation won't solve.

That's true, and at the end of the day if a user needs a non-caching plan_fft function they could allocate a new `FFTPlanner` each time. I guess since it can be worked around for now and adding such a function can be done in a backwards-compatible way, this isn't a blocker for 2.0 either.

So it looks like the only thing I can see to change for 2.0 would be moving from `Rc` to `Arc` to enable `Sync` for `FFT`.

**Comment by ejmahler** [comment]
One more thing I have on my mind: Should the constructors of various FFT algorithms return Result<> objects instead of panicing on invalid input? For example, for Radix4, if the user passes in a  size that isn't a power of two, we could return an Err() with a message saying the size isn't valid, rather than an assert resulting in a panic. The same could be used for GoodThomasAlgorithm to make sure gcd(a, b) == 1, for MixedRadix to make sure a.is_inverse() == b.is_inverse(), etc.

Or do you think the asserts are fine? I think in the actual process methods, the assert() is fine because it matches the API of a slice, where it panics if you give an invalid slice size etc.

I think either could work.

**Comment by awelkie** [comment]
I think the asserts are fine, since it's an error in using the API and not
a runtime error or an error generated by our code

**Comment by awelkie** [comment]
https://crates.io/crates/rustfft/2.0.0
