### ISSUE TITLE
rustfft fails to build

### ISSUE THREAD

**Issue by pavelmachek** [awelkie/RustFFT#30]
I've tried adding basic_dsp_matrix = "0.5.2" to Cargo.toml for correlation computation. That pulls in rustfft. Unfortunately, rustfft compilation fails:

Architecture is i686 (32bit). Any ideas?

```
   Compiling rustfft v2.0.0
error[E0369]: binary operation `*` cannot be applied to type `num_complex::Complex<T>`
  --> /data/pavel/.cargo/registry/src/github.com-1ecc6299db9ec823/rustfft-2.0.0/src/algorithm/mixed_radix.rs:95:24
   |
95 |             *element = *element * twiddle;
   |                        ^^^^^^^^^^^^^^^^^^
   |
   = note: an implementation of `std::ops::Mul` might be missing for `num_complex::Complex<T>`
...
error[E0369]: binary operation `*` cannot be applied to type `&num_complex::Complex<T>`
   --> /data/pavel/.cargo/registry/src/github.com-1ecc6299db9ec823/rustfft-2.0.0/src/algorithm/butterflies.rs:717:41
    |
717 |         *buffer.get_unchecked_mut(15) = buffer.get_unchecked(15) * twiddle9;
    |                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |
    = note: an implementation of `std::ops::Mul` might be missing for `&num_complex::Complex<T>`

error: aborting due to 73 previous errors

error: Could not compile `rustfft`.
```

**Comment by pavelmachek** [comment]
I tried cargo +nightly run, but result is pretty similar:

```
error[E0369]: binary operation `*` cannot be applied to type `&num_complex::Complex<T>`
   --> /data/pavel/.cargo/registry/src/github.com-1ecc6299db9ec823/rustfft-2.0.0/src/algorithm/butterflies.rs:717:41
    |
717 |         *buffer.get_unchecked_mut(15) = buffer.get_unchecked(15) * twiddle9;
    |                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |
    = note: an implementation of `std::ops::Mul` might be missing for `&num_complex::Complex<T>`

error: aborting due to 73 previous errors

You've got a few errors: E0277, E0308, E0369, E0599, E0600
If you want more information on an error, try using "rustc --explain E0277"
error: Could not compile `rustfft`.
warning: build failed, waiting for other jobs to finish...
error: build failed
```

**Comment by liebharc** [comment]
Hi,

Could you please post the exact version of num-complex which is pulled during the builds? And the output of rustc --version?

I don't have a computer available right now, but the builds on Travis still succeed, e.g.: https://travis-ci.org/liebharc/basic_dsp/builds/273122016
Perhaps we find a clue by comparing your version numbers to the ones in the Travis log.

**Comment by pavelmachek** [comment]
Thanks for quick reply.

num-complex seems to be 0.1.43:

```
       Fresh adler32 v1.0.2
       Fresh lazy_static v0.2.11
       Fresh rustc-serialize v0.3.24
       Fresh openssl-probe v0.1.2
       Fresh libc v0.2.36
       Fresh bitflags v1.0.1
       Fresh num-traits v0.2.1
       Fresh nodrop v0.1.12
       Fresh num-traits v0.1.41
       Fresh cc v1.0.4
       Fresh c_vec v1.2.1
       Fresh pkg-config v0.3.9
       Fresh crossbeam v0.3.2
       Fresh byteorder v1.2.1
       Fresh cfg-if v0.1.2
       Fresh inflate v0.3.3
       Fresh time v0.1.39
       Fresh num_cpus v1.8.0
       Fresh num-complex v0.1.43
       Fresh arrayvec v0.4.7
       Fresh num-integer v0.1.35
       Fresh deflate v0.7.17
       Fresh socket2 v0.3.0
   Compiling rustfft v2.0.0
       Fresh num-iter v0.1.34
     Running `rustc --crate-name rustfft
```

pavel@duo:~/g/tui/nowcast/rnowcast$ rustc --version
rustc 1.24.1 (d3ae9a9e0 2018-02-27)

Which seems to be same version as in travis. But I seem to have older
num-traits... let me try cargo update...?

Aha, so after cargo update num-traits is updated and compile
succeeds. Thanks for the help!

**Comment by ejmahler** [comment]
I see both this:
Fresh num-traits v0.2.1
and this:
Fresh num-traits v0.1.41

Is it possible that you've got two competing num-traits versions?

https://github.com/rust-num/num-traits/blob/master/RELEASES.md it doesn't look like num-traits had any breaking changes even with its 2.0 release except for a no-std addition, but it might still be getting confused because of the version mismatch between one library and another

**Comment by liebharc** [comment]
I think num-complex pulls the 0.2 version of num-traits. Rustfft and basic-dsp-vector pull the 0.1 version of num-traits. Since it affects only the traits, it could go well. As I could imagine that e.g. Complex32 and Complex64 just get both trait versions (0.1 and 0.2) and the Rust compiler picks whichever version it needs. However it might be a good idea to update the rustfft dependency of num-traits to resolve that issue (and I would need to do the same for basic-dsp-vector). I would need to double check, but I believe this would only be a patch release according to semver.
