### ISSUE TITLE
Use SIMD

### ISSUE THREAD

**Issue by jimrybarski** [awelkie/RustFFT#40]
Would it be feasible and beneficial to add SIMD instructions?

**Comment by ejmahler** [comment]
I haven’t tested it, but I bet it would.

If you want to do a little of this yourself, a good place to start would be
some simple loops. In mixed_radix.rs, search for “// STEP 3: Apply twiddle
factors”

On one hand, this loop is simple enough that it would be easy to convert to
a SIMD iterator. On the other hand, it’s simple enough that he compiler
might be automatically converting it. So a helpful place for you to start
would be, what is the compiler currently putting out for this loop in
optimized builds?

If it turns out that it’s not already putting out simd instrucions, I can
think of several simple loops like that that wcould be easily converted to
a SIMD iterator

**Comment by ejmahler** [comment]
For a more complicated function that might benefit, check out “butterfly_4”
in radix4.rs. This would require more thinking to convert, but I bet the
compiler has a harder time auto-converting it

**Comment by superblaubeere27** [comment]
I looked into the assembly of DFT and there is definitely no auto-vectorization going on. I will try to fix it and create a PR afterward

**Comment by ejmahler** [comment]
Hi @superblaubeere27 and @jimrybarski you might be interested to know that in the "simd" branch, I currently have an AVX implementation that outperforms FFTW.

It's not ready for release yet (Requires nightly, will fail to compile if you're not targeting x86_64, no way to opt-out of all the AVX code, way too much unsafe) but if you want some faster FFTs, I would love to have someone test it out!

**Comment by ejmahler** [comment]
The simd branch in my own fork https://github.com/ejmahler/RustFFT/tree/simd

**Comment by ejmahler** [comment]
RustFFT 5.0 has an implementation of AVX. I will implement SSE Some Time Soon, and neon/avx512 when i can get a machine to test them on + rust stabilizes them.

FYI, all rust developemt will be happening in https://github.com/ejmahler/RustFFT from now on.
