### ISSUE TITLE
FFT plot mismatches input frequencies

### ISSUE THREAD

**Issue by italic-r** [awelkie/RustFFT#58]
Some details:
Rust 1.40.0 stable
`rustfft` 3.0.1
`gnuplot` 0.0.34

The last few days I've been trying to figure out how to work with FFts. I'm artificially generating a sine signal (or several) and running them through rustfft, then plotting with gnuplot. However, the FFT plotting indicates the signal is not what I had put in. For example, I put in a 600 Hz wave and the plot shows the peak at 450 Hz. This a minimal example based on my scratch file:

```rust
use gnuplot::*;
use sample::{
    signal,
    Signal
};
use rustfft::{
    FFT,
    FFTplanner,
    algorithm::Radix4,
    num_complex::Complex,
    num_traits::Zero
};

fn _min_ex() {
    let fft_inverse = false;
    let fft_size = 4096;
    let samp_rate = 48000.;
    let samp_len = fft_size;
    let _ex_len = 2000;

    // signals
    let _sig1:  Vec<f32> = signal::rate(samp_rate).const_hz( 600.).sine().take(samp_len).map(|val| val[0] as f32).collect();
    let _sig2:  Vec<f32> = signal::rate(samp_rate).const_hz(1500.).sine().take(samp_len).map(|val| val[0] as f32).collect();
    let _join: Vec<f32> = _sig1.iter().zip(_sig2.iter()).map(|tup| tup.0 + tup.1).collect();

    // fft input/output
    let mut input: Vec<Complex<f32>> = _join.iter().map(|val| Complex::from(val)).collect();
    let mut output = vec![Zero::zero(); samp_len];

    // fft
    let mut planner = FFTplanner::new(fft_inverse);
    let fft = planner.plan_fft(samp_len);
    fft.process(&mut input, &mut output);

    // normalize
    output.truncate(_ex_len);
    let out_graph = output
        .iter()
        .map(|val| val.norm()
            / fft.len() as f32
            );

    let mut fg = gnuplot::Figure::new();
    fg.axes2d().set_title("fft", &[]).lines(0..fft.len(), out_graph, &[]);
    fg.show().unwrap();
}
```
This is the resulting plot:
![plot](https://user-images.githubusercontent.com/3143630/73301872-7925b380-41c8-11ea-8b17-9c897dd236fe.jpg)

Clearly the input signals are 600 Hz and 1500 Hz superimposed, but the graph is showing the plot significantly lower. Plotting one sine at a time results in the same peaks, so it's not a signal mixing or normalization issue. Furthermore, grabbing audio from a sound device produces similar discrepancies and does not match other FFT plots.

**Comment by ejmahler** [comment]
I think there's a misunderstanding here over exactly what the frequency values of the FFT represent.

I can't build your example because the signal crate appears to be unix-only, but from reading it, I assume that `signal::rate` returns an iterator of 48,000 elements corresponding to samples over one second of real time. Then, you specify a frequency of 500 and 1600 to be carried by those 48,000 samples per second. Finally, you call `.take()`.

`iterator::take(n)` omits everything after `n` elements. So `_sig1`, `_sig2`, and `_join` effectively contain `fft_size/samp_rate` seconds worth of frequency data, IE roughly 0.085 seconds, or 1/11.7 of a second.

But your graph doesn't account for this factor of 1/11.7. The frequencies listed there assume that the sample rate is 4096 (IE the size of the FFT). To convert back to a sample rate of 48000, you need to multiply the X axis by `sample_rate/fft_size`. Eyeballing the gnuplot chart you shared, it looks like you'll get your expected frequencies back that way.

**Comment by italic-r** [comment]
That's very interesting... I adjusted my sample rate and FFT size in two tests and they both resulted in proper frequency plotting. This would explain some behavior in other DSP/FFT display software. If you lower the FFT size for the same bandwidth and display it, the display (pixel in this case) covers more screen area than larger FFT sizes. This scaling would explain that effect.

My question now is how would I scale the data in the X axis? I think the most straight-forward way would be to duplicate the data in cases where the FFT is smaller than the sample rate, and average for cases where it is larger, but that seems pretty resource-intensive for realtime processing. Would you do this differently?

**Comment by ejmahler** [comment]
It seems like something you should handle in the logic of whateveris processing the FFT output.

Without knowing exactly what you're doing it's hard to say what that means, but I would advise against changing the FFT size so that the output buckets are the right size. Instead, write whatever is consuming the FFT data to know that it needs to scale the frequency represented by each bucket.

**Comment by italic-r** [comment]
Makes sense to me. That's how I was envisioning it. Thanks!
