### ISSUE TITLE
Support for "early cutoff"

### ISSUE THREAD

**Issue by PvdBerg1998** [awelkie/RustFFT#64]
Thanks for the great project!

I was wondering if it is possible to support calculating only the first few N FFT components. An example usecase would be BlurHash (https://github.com/woltapp/blurhash). I know this should be easily done using a regular, naive FFT, but I have no clue if this is possible with more sophisticated algorithms.

**Comment by ejmahler** [comment]
Just FYI, development is done in https://github.com/ejmahler/RustFFT

If you're only doing 3-4 elements like blurhash does, then I don't think you'll do better than copy/pasting the [DFT](https://github.com/ejmahler/RustFFT/blob/master/src/algorithm/dft.rs#L41) struct and editing the inner or outer loop (depending on whether you only want the first 4 inputs or first 4 outputs) to only loop N times instead of looping over the entire input/output.
